@startuml market_cloths

' Styling
skinparam class {
  BackgroundColor #FDF6E3
  BorderColor #657B83
  BorderThickness 1
  ArrowColor Black
}

' Category Collection
class Category {
  + id: string
  name: string
  description: string
}

' Product Collection
class Product {
  + id: string
  name: string
  description: string
  createdAt: timestamp
  image_url: List<string>
  price: number
  stok: number
  categoryId: string
}

' User Collection
class User {
  + id: string
  email: string
  password: string
  role: string <<user | admin>>
  makanan_favorite: string
}

' Refresh Token Collection
class RefreshToken {
  + id: string
  createdAt: timestamp
  expiresAt: timestamp
  revoke: boolean
  token: string
  userId: string
}

' Sales Collection
class Sales {
  + id: string
  userId: string
  items: List<{
    productId: string
    name: string
    price: number
    quantity: number
  }>
  totalAmount: number
  createdAt: timestamp
  paymentStatus: string <<paid | pending | failed>>
}

' Relationships
Product --> Category : categoryId
Sales --> User : userId
RefreshToken --> User : userId

@enduml
