@startuml market_cloths

' Styling
skinparam class {
  BackgroundColor #FDF6E3
  BorderColor #657B83
  BorderThickness 1
  ArrowColor Black
}

' Category Collection
class Category {
  + id: string
  name: string
  description: string
}

' Product Collection
class Product {
  + id: string
  name: string
  description: string
  createdAt: timestamp
  image_url: List<string>
  price: number
  stok: number
  categoryName: string
}

' User Collection
class User {
  + id: string
  email: string
  password: string
  role: string <<user | admin>>
  makanan_favorite: string
}

' Refresh Token Collection
class RefreshToken {
  + id: string
  createdAt: timestamp
  expiresAt: timestamp
  revoke: boolean
  token: string
  userId: string
}



' Relationships
Product --> Category : categoryId
RefreshToken --> User : userId

@enduml
